services:
  churn-api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    depends_on:
      - churn-api


volumes:
  prometheus-data: